[tools]
rojo = { source = "rojo-rbx/rojo", version = "7" }
selene = { source = "Kampfkarren/selene", version = "0.24.0"}
stylua = { source = "JohnnyMorganz/StyLua", version = "0.16.1"}
rbxcloud = { github = "Sleitnick/rbxcloud", version = "0.3.0" }
remodel = { source = "rojo-rbx/remodel", version = "0.11.0" }