name: Deploy_Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # The type of runner that the job will run on
    name: Deploy_product
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
     - uses: Roblox/setup-foreman@v1
        name: Install Foreman
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - run: rojo build -o Tycoon.rbxl

      - run: rbxcloud experience publish --filename Tycoon.rbxl  --place-id 12715780249 --universe-id 4456983158 --version-type published --api-key ${{ secrets.API_KEY_STAGE}}