name: Deploy_Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  deploy:
    name: Deploy_Stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o assets/Tycoon.rbxl

    - run: rbxcloud experience publish --filename assets/Tycoon.rbxl  --place-id 12698546053 --universe-id 4451997071 --version-type published --api-key ${{ secrets.API_KEY_STAGE}}
