name: Deploy_Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Only run the workflow for the main branc
    tag:
    # Only run the workflow for the main branch 
    - 'v*'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  deploy:
    name: Deploy_product
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o Tycoon.rbxl

    - run: rbxcloud experience publish --filename Tycoon.rbxl  --place-id 12715780249 --universe-id 4456983158 --version-type published --api-key ${{ secrets.API_KEY_STAGE}}
